import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { SEVERITY_LABEL, SEVERITY_ORDER, type Severity } from "@/lib/severity";

const SEVERITY_HEX: Record<Severity, string> = {
  critical: "#dc4444",
  high: "#e08a3c",
  medium: "#c9a227",
  low: "#4b8bc4",
};

export interface ReportFinding {
  id: string;
  severity: Severity;
  title: string;
  description: string | null;
  file_path: string | null;
  line_number: number | null;
  ai_explanation: string | null;
  ai_fix_suggestion: string | null;
}

export interface ReportData {
  targetIdentifier: string;
  targetType: "repo" | "site";
  scanId: string;
  scanDate: string;
  findings: ReportFinding[];
}

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica", color: "#1a1a1a" },
  h1: { fontSize: 20, fontWeight: 700, marginBottom: 4 },
  subtitle: { fontSize: 10, color: "#666666", marginBottom: 24 },
  h2: { fontSize: 14, fontWeight: 700, marginTop: 20, marginBottom: 10 },
  summaryRow: { flexDirection: "row", gap: 12, marginBottom: 20 },
  summaryBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#e5e5e5",
    borderRadius: 6,
    padding: 10,
    alignItems: "center",
  },
  summaryCount: { fontSize: 20, fontWeight: 700 },
  summaryLabel: { fontSize: 9, color: "#666666", marginTop: 2 },
  finding: { borderWidth: 1, borderColor: "#e5e5e5", borderRadius: 6, padding: 10, marginBottom: 8 },
  findingHeader: { flexDirection: "row", alignItems: "center", marginBottom: 6, gap: 6 },
  severityDot: { width: 6, height: 6, borderRadius: 3 },
  findingTitle: { fontSize: 11, fontWeight: 700, flex: 1 },
  findingMeta: { fontSize: 8, color: "#888888" },
  sectionLabel: { fontSize: 8, fontWeight: 700, color: "#888888", marginTop: 6, marginBottom: 2 },
  body: { fontSize: 9, lineHeight: 1.4 },
  footer: { position: "absolute", bottom: 20, left: 40, right: 40, fontSize: 8, color: "#999999" },
});

export function ScanReportDocument({ data }: { data: ReportData }) {
  const counts: Record<Severity, number> = { critical: 0, high: 0, medium: 0, low: 0 };
  for (const f of data.findings) counts[f.severity] += 1;

  return (
    <Document title={`Vibecoder Scanner Report — ${data.targetIdentifier}`}>
      <Page size="A4" style={styles.page}>
        <Text style={styles.h1}>Security Scan Report</Text>
        <Text style={styles.subtitle}>
          {data.targetIdentifier} ({data.targetType === "repo" ? "GitHub repository" : "live site"}) ·
          Scanned {data.scanDate}
        </Text>

        <Text style={styles.h2}>Executive summary</Text>
        <View style={styles.summaryRow}>
          {SEVERITY_ORDER.map((sev) => (
            <View key={sev} style={styles.summaryBox}>
              <Text style={[styles.summaryCount, { color: SEVERITY_HEX[sev] }]}>{counts[sev]}</Text>
              <Text style={styles.summaryLabel}>{SEVERITY_LABEL[sev]}</Text>
            </View>
          ))}
        </View>
        <Text style={styles.body}>
          {data.findings.length === 0
            ? "No issues were found in this scan."
            : `This scan found ${data.findings.length} issue${
                data.findings.length === 1 ? "" : "s"
              }. Critical and high-severity issues should be addressed first — see the appendix below for a plain-language explanation and a concrete fix for each.`}
        </Text>

        <Text style={styles.h2}>Findings</Text>
        {SEVERITY_ORDER.flatMap((sev) => data.findings.filter((f) => f.severity === sev)).map((f) => (
          <View key={f.id} style={styles.finding} wrap={false}>
            <View style={styles.findingHeader}>
              <View style={[styles.severityDot, { backgroundColor: SEVERITY_HEX[f.severity] }]} />
              <Text style={styles.findingTitle}>{f.title}</Text>
              <Text style={styles.findingMeta}>{SEVERITY_LABEL[f.severity]}</Text>
            </View>
            {f.file_path && (
              <Text style={styles.findingMeta}>
                {f.file_path}
                {f.line_number ? `:${f.line_number}` : ""}
              </Text>
            )}
            <Text style={styles.sectionLabel}>WHAT THIS MEANS</Text>
            <Text style={styles.body}>{f.ai_explanation ?? f.description ?? "No description available."}</Text>
            {f.ai_fix_suggestion && (
              <>
                <Text style={styles.sectionLabel}>SUGGESTED FIX</Text>
                <Text style={styles.body}>{f.ai_fix_suggestion}</Text>
              </>
            )}
          </View>
        ))}

        <Text style={styles.footer} fixed>
          Generated by Vibecoder Scanner — scan {data.scanId}
        </Text>
      </Page>
    </Document>
  );
}
